# Generated by Django 5.0.1 on 2025-11-06 10:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "restaurant_type",
                    models.CharField(
                        choices=[
                            ("FINE_DINING", "Fine Dining"),
                            ("CASUAL_DINING", "Casual Dining"),
                            ("FAST_FOOD", "Fast Food"),
                            ("CAFE", "Café"),
                            ("BAR", "Bar/Pub"),
                            ("BAKERY", "Bakery"),
                            ("FOOD_TRUCK", "Food Truck"),
                            ("CLOUD_KITCHEN", "Cloud Kitchen"),
                            ("OTHER", "Other"),
                        ],
                        default="CASUAL_DINING",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("website", models.URLField(blank=True, null=True)),
                ("address_line1", models.CharField(max_length=255)),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="restaurants/logos/"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="restaurants/covers/"
                    ),
                ),
                (
                    "operating_hours",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Operating hours for each day of the week",
                    ),
                ),
                ("accepts_dine_in", models.BooleanField(default=True)),
                ("accepts_takeout", models.BooleanField(default=True)),
                ("accepts_delivery", models.BooleanField(default=False)),
                ("accepts_reservations", models.BooleanField(default=False)),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Tax rate in percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "service_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Service charge in percentage",
                        max_digits=5,
                    ),
                ),
                ("accepts_cash", models.BooleanField(default=True)),
                ("accepts_cards", models.BooleanField(default=True)),
                ("accepts_mobile_payment", models.BooleanField(default=False)),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("FREE", "Free Plan"),
                            ("BASIC", "Basic Plan"),
                            ("PROFESSIONAL", "Professional Plan"),
                            ("ENTERPRISE", "Enterprise Plan"),
                        ],
                        default="FREE",
                        max_length=20,
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("TRIAL", "Trial"),
                        ],
                        default="TRIAL",
                        max_length=20,
                    ),
                ),
                ("subscription_start_date", models.DateField(blank=True, null=True)),
                ("subscription_end_date", models.DateField(blank=True, null=True)),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "settings",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional settings"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        limit_choices_to={
                            "role__in": ["RESTAURANT_OWNER", "PLATFORM_ADMIN"]
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_restaurants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Restaurant",
                "verbose_name_plural": "Restaurants",
                "db_table": "restaurants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RestaurantSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("whatsapp_notifications", models.BooleanField(default=False)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("auto_accept_orders", models.BooleanField(default=False)),
                (
                    "min_order_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "max_order_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "estimated_prep_time",
                    models.IntegerField(
                        default=30, help_text="Average preparation time in minutes"
                    ),
                ),
                (
                    "delivery_radius",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Delivery radius in km",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "free_delivery_above",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("total_tables", models.IntegerField(default=0)),
                ("enable_table_qr", models.BooleanField(default=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("language", models.CharField(default="en", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detailed_settings",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Restaurant Settings",
                "verbose_name_plural": "Restaurant Settings",
                "db_table": "restaurant_settings",
            },
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(fields=["slug"], name="restaurants_slug_0c26aa_idx"),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["subscription_status"], name="restaurants_subscri_1c9004_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["is_active"], name="restaurants_is_acti_05aaa6_idx"
            ),
        ),
    ]
