# Generated by Django 5.2.8 on 2025-11-05 18:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="bio")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="avatar",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="location"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "xp",
                    models.BigIntegerField(default=0, verbose_name="experience points"),
                ),
                ("level", models.PositiveIntegerField(default=1, verbose_name="level")),
                (
                    "current_streak",
                    models.PositiveIntegerField(
                        default=0, verbose_name="current streak"
                    ),
                ),
                (
                    "longest_streak",
                    models.PositiveIntegerField(
                        default=0, verbose_name="longest streak"
                    ),
                ),
                (
                    "last_activity_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="last activity date"
                    ),
                ),
                ("credits", models.IntegerField(default=10, verbose_name="credits")),
                (
                    "credits_expiry",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="credits expiry"
                    ),
                ),
                (
                    "total_credits_earned",
                    models.BigIntegerField(
                        default=10, verbose_name="total credits earned"
                    ),
                ),
                (
                    "total_credits_spent",
                    models.BigIntegerField(
                        default=0, verbose_name="total credits spent"
                    ),
                ),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("pro", "Pro"),
                            ("unlimited", "Unlimited"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="subscription tier",
                    ),
                ),
                (
                    "subscription_start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="subscription start date"
                    ),
                ),
                (
                    "subscription_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="subscription end date"
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Stripe customer ID"
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Stripe subscription ID",
                    ),
                ),
                (
                    "is_coach",
                    models.BooleanField(default=False, verbose_name="is coach"),
                ),
                (
                    "verified_coach",
                    models.BooleanField(default=False, verbose_name="verified coach"),
                ),
                ("coach_bio", models.TextField(blank=True, verbose_name="coach bio")),
                (
                    "coach_expertise",
                    models.JSONField(default=list, verbose_name="coach expertise"),
                ),
                (
                    "coach_hourly_rate_credits",
                    models.PositiveIntegerField(
                        default=50, verbose_name="coach hourly rate (credits)"
                    ),
                ),
                (
                    "coach_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        verbose_name="coach rating",
                    ),
                ),
                (
                    "coach_total_sessions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total coaching sessions"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="staff status"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(default=False, verbose_name="email verified"),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", max_length=10, verbose_name="language"
                    ),
                ),
                (
                    "timezone_name",
                    models.CharField(
                        default="UTC", max_length=50, verbose_name="timezone"
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="email notifications"
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(
                        default=True, verbose_name="push notifications"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="Friend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_of",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "friend",
                "verbose_name_plural": "friends",
                "ordering": ["-created_at"],
                "unique_together": {("user", "friend")},
            },
        ),
        migrations.CreateModel(
            name="FriendRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "friend request",
                "verbose_name_plural": "friend requests",
                "ordering": ["-created_at"],
                "unique_together": {("from_user", "to_user")},
            },
        ),
    ]
