# Generated by Django 5.0.1 on 2025-11-06 10:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("menus", "0001_initial"),
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerBehavior",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preferred_order_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "preferred_time_slot",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "order_frequency",
                    models.IntegerField(default=0, help_text="Orders per month"),
                ),
                ("top_categories", models.JSONField(blank=True, default=list)),
                ("top_items", models.JSONField(blank=True, default=list)),
                ("last_order_date", models.DateField(blank=True, null=True)),
                ("days_since_last_order", models.IntegerField(default=0)),
                (
                    "is_at_risk",
                    models.BooleanField(
                        default=False, help_text="Customer hasn't ordered in a while"
                    ),
                ),
                (
                    "lifetime_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_data",
                        to="customers.customer",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_behaviors",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Behavior",
                "verbose_name_plural": "Customer Behaviors",
                "db_table": "customer_behaviors",
                "unique_together": {("customer", "restaurant")},
            },
        ),
        migrations.CreateModel(
            name="DailySalesReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("total_orders", models.IntegerField(default=0)),
                ("dine_in_orders", models.IntegerField(default=0)),
                ("takeout_orders", models.IntegerField(default=0)),
                ("delivery_orders", models.IntegerField(default=0)),
                ("cancelled_orders", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "tax_collected",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "tips_collected",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "discounts_given",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "average_preparation_time",
                    models.IntegerField(default=0, help_text="In minutes"),
                ),
                ("unique_customers", models.IntegerField(default=0)),
                ("new_customers", models.IntegerField(default=0)),
                ("returning_customers", models.IntegerField(default=0)),
                ("hourly_breakdown", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_sales",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Sales Report",
                "verbose_name_plural": "Daily Sales Reports",
                "db_table": "daily_sales_reports",
                "ordering": ["-date"],
                "unique_together": {("restaurant", "date")},
            },
        ),
        migrations.CreateModel(
            name="MenuItemAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("times_ordered", models.IntegerField(default=0)),
                ("quantity_sold", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "cost_of_goods",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "profit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="menus.menuitem",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_analytics",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Item Analytics",
                "verbose_name_plural": "Menu Item Analytics",
                "db_table": "menu_item_analytics",
                "ordering": ["-date"],
                "unique_together": {("menu_item", "date")},
            },
        ),
    ]
