# Generated by Django 5.2.8 on 2025-11-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[
                            ("DOMAIN", "Domaine personnalisé"),
                            ("BOOST", "Boost visibilité"),
                            ("WHATSAPP", "WhatsApp forfait"),
                        ],
                        max_length=20,
                        verbose_name="type d'abonnement",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="prix mensuel"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(auto_now_add=True, verbose_name="date de début"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="date de fin"),
                ),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=True, verbose_name="renouvellement automatique"
                    ),
                ),
            ],
            options={
                "verbose_name": "abonnement",
                "verbose_name_plural": "abonnements",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="montant"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="devise"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("COMPLETED", "Complété"),
                            ("FAILED", "Échec"),
                            ("REFUNDED", "Remboursé"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(max_length=50, verbose_name="méthode de paiement"),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="ID transaction"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="complété le"
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction",
                "verbose_name_plural": "transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
