# Generated by Django 5.2.8 on 2025-11-05 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("custom", "Custom"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="frequency",
                    ),
                ),
                (
                    "custom_frequency_days",
                    models.PositiveIntegerField(
                        default=1, verbose_name="custom frequency (days)"
                    ),
                ),
                (
                    "completed_dates",
                    models.JSONField(default=list, verbose_name="completed dates"),
                ),
                (
                    "xp_per_completion",
                    models.PositiveIntegerField(
                        default=10, verbose_name="XP per completion"
                    ),
                ),
                (
                    "current_streak",
                    models.PositiveIntegerField(
                        default=0, verbose_name="current streak"
                    ),
                ),
                (
                    "best_streak",
                    models.PositiveIntegerField(default=0, verbose_name="best streak"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "action",
                "verbose_name_plural": "actions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoalLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "goal like",
                "verbose_name_plural": "goal likes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "target_date",
                    models.DateField(blank=True, null=True, verbose_name="target date"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="completed"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "xp_reward",
                    models.PositiveIntegerField(default=50, verbose_name="XP reward"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "milestone",
                "verbose_name_plural": "milestones",
                "ordering": ["order", "target_date"],
            },
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="completed"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "step",
                "verbose_name_plural": "steps",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="category"
                    ),
                ),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("friends", "Friends Only"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=20,
                        verbose_name="privacy",
                    ),
                ),
                (
                    "is_template",
                    models.BooleanField(default=False, verbose_name="is template"),
                ),
                (
                    "is_premium_template",
                    models.BooleanField(
                        default=False, verbose_name="is premium template"
                    ),
                ),
                (
                    "template_credit_cost",
                    models.PositiveIntegerField(
                        default=0, verbose_name="template credit cost"
                    ),
                ),
                (
                    "template_downloads",
                    models.PositiveIntegerField(
                        default=0, verbose_name="template downloads"
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="progress percentage",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="completed"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "likes_count",
                    models.PositiveIntegerField(default=0, verbose_name="likes count"),
                ),
                (
                    "cheers_count",
                    models.PositiveIntegerField(default=0, verbose_name="cheers count"),
                ),
                (
                    "comments_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="comments count"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "original_goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replicas",
                        to="goals.goal",
                    ),
                ),
            ],
            options={
                "verbose_name": "goal",
                "verbose_name_plural": "goals",
                "ordering": ["-created_at"],
            },
        ),
    ]
