# Generated by Django 5.2.8 on 2025-11-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artworks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nom")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        upload_to="galleries/",
                        verbose_name="image de couverture",
                    ),
                ),
                (
                    "layout_type",
                    models.CharField(
                        choices=[
                            ("GRID", "Grille"),
                            ("CAROUSEL", "Carrousel"),
                            ("MASONRY", "Mosaïque"),
                        ],
                        default="GRID",
                        max_length=20,
                        verbose_name="type de mise en page",
                    ),
                ),
                ("is_public", models.BooleanField(default=True, verbose_name="public")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "galerie",
                "verbose_name_plural": "galeries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Exhibition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="titre")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("start_date", models.DateField(verbose_name="date de début")),
                ("end_date", models.DateField(verbose_name="date de fin")),
                (
                    "is_virtual",
                    models.BooleanField(default=True, verbose_name="virtuel"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "artworks",
                    models.ManyToManyField(
                        related_name="exhibitions",
                        to="artworks.artwork",
                        verbose_name="œuvres",
                    ),
                ),
            ],
            options={
                "verbose_name": "exposition",
                "verbose_name_plural": "expositions",
                "ordering": ["-start_date"],
            },
        ),
    ]
