# Generated by Django 5.2.8 on 2025-11-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("goal_created", "Goal Created"),
                            ("goal_completed", "Goal Completed"),
                            ("milestone_completed", "Milestone Completed"),
                            ("action_completed", "Action Completed"),
                            ("badge_earned", "Badge Earned"),
                            ("level_up", "Level Up"),
                            ("template_created", "Template Created"),
                            ("template_used", "Template Used"),
                            ("cheer_given", "Cheer Given"),
                            ("comment_posted", "Comment Posted"),
                        ],
                        max_length=50,
                        verbose_name="activity type",
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "related_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                ("metadata", models.JSONField(default=dict, verbose_name="metadata")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="timestamp"),
                ),
            ],
            options={
                "verbose_name": "activity log",
                "verbose_name_plural": "activity logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="GoalAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_actions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total actions"
                    ),
                ),
                (
                    "completed_actions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="completed actions"
                    ),
                ),
                (
                    "completion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="completion rate",
                    ),
                ),
                (
                    "average_completion_time_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="average completion time (days)"
                    ),
                ),
                (
                    "estimated_completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="estimated completion date"
                    ),
                ),
                (
                    "total_views",
                    models.PositiveIntegerField(default=0, verbose_name="total views"),
                ),
                (
                    "unique_visitors",
                    models.PositiveIntegerField(
                        default=0, verbose_name="unique visitors"
                    ),
                ),
                (
                    "most_productive_day",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="most productive day"
                    ),
                ),
                (
                    "most_productive_time",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="most productive time"
                    ),
                ),
                (
                    "consistency_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="consistency score",
                    ),
                ),
                (
                    "last_calculated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last calculated at"
                    ),
                ),
            ],
            options={
                "verbose_name": "goal analytics",
                "verbose_name_plural": "goal analytics",
            },
        ),
        migrations.CreateModel(
            name="UserAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_goals",
                    models.PositiveIntegerField(default=0, verbose_name="total goals"),
                ),
                (
                    "active_goals",
                    models.PositiveIntegerField(default=0, verbose_name="active goals"),
                ),
                (
                    "completed_goals",
                    models.PositiveIntegerField(
                        default=0, verbose_name="completed goals"
                    ),
                ),
                (
                    "goal_completion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="goal completion rate",
                    ),
                ),
                (
                    "total_actions_completed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total actions completed"
                    ),
                ),
                (
                    "total_milestones_completed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total milestones completed"
                    ),
                ),
                (
                    "days_active",
                    models.PositiveIntegerField(default=0, verbose_name="days active"),
                ),
                (
                    "most_productive_day",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="most productive day"
                    ),
                ),
                (
                    "most_productive_hour",
                    models.PositiveIntegerField(
                        default=0, verbose_name="most productive hour"
                    ),
                ),
                (
                    "average_daily_actions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="average daily actions",
                    ),
                ),
                (
                    "consistency_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="consistency score",
                    ),
                ),
                (
                    "total_cheers_given",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total cheers given"
                    ),
                ),
                (
                    "total_cheers_received",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total cheers received"
                    ),
                ),
                (
                    "total_comments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total comments"
                    ),
                ),
                (
                    "templates_created",
                    models.PositiveIntegerField(
                        default=0, verbose_name="templates created"
                    ),
                ),
                (
                    "templates_downloaded",
                    models.PositiveIntegerField(
                        default=0, verbose_name="templates downloaded"
                    ),
                ),
                (
                    "last_calculated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last calculated at"
                    ),
                ),
            ],
            options={
                "verbose_name": "user analytics",
                "verbose_name_plural": "user analytics",
            },
        ),
    ]
