# Generated by Django 5.2.8 on 2025-11-05 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artworks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="prix"
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="commission",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="montant total"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PAID", "Payé"),
                            ("SHIPPED", "Expédié"),
                            ("DELIVERED", "Livré"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="payé le"),
                ),
            ],
            options={
                "verbose_name": "commande",
                "verbose_name_plural": "commandes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "starting_bid",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="enchère de départ",
                    ),
                ),
                (
                    "current_bid",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="enchère actuelle"
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="début")),
                ("end_date", models.DateTimeField(verbose_name="fin")),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "artwork",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auction",
                        to="artworks.artwork",
                        verbose_name="œuvre",
                    ),
                ),
            ],
            options={
                "verbose_name": "enchère",
                "verbose_name_plural": "enchères",
                "ordering": ["-end_date"],
            },
        ),
    ]
