# Generated by Django 5.2.8 on 2025-11-05 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artworks", "0002_initial"),
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_auctions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="gagnant",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="artwork",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="artworks.artwork",
                verbose_name="œuvre",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="acheteur",
            ),
        ),
    ]
