# Generated by Django 5.2.8 on 2025-11-05 19:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="adresse email"
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("ARTIST", "Artiste"),
                            ("GALLERY", "Galerie"),
                            ("COLLECTOR", "Collectionneur"),
                            ("USER", "Utilisateur"),
                            ("ADMIN", "Administrateur"),
                        ],
                        default="USER",
                        max_length=20,
                        verbose_name="type d'utilisateur",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nom complet"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="biographie")),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profiles/",
                        verbose_name="photo de profil",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="covers/",
                        verbose_name="image de couverture",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="téléphone"
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="site web",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="adresse"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="ville"),
                ),
                (
                    "country",
                    models.CharField(
                        default="France", max_length=100, verbose_name="pays"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="code postal"
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                ("twitter_url", models.URLField(blank=True, verbose_name="Twitter/X")),
                ("linkedin_url", models.URLField(blank=True, verbose_name="LinkedIn")),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "English"),
                            ("es", "Español"),
                        ],
                        default="fr",
                        max_length=5,
                        verbose_name="langue préférée",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="vérifié"),
                ),
                (
                    "verification_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de vérification"
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="méthode de vérification",
                    ),
                ),
                (
                    "is_sage",
                    models.BooleanField(
                        default=False, verbose_name="membre du Conseil des Sages"
                    ),
                ),
                (
                    "sage_since",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="sage depuis"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="dernière IP de connexion"
                    ),
                ),
                (
                    "newsletter_subscribed",
                    models.BooleanField(
                        default=True, verbose_name="abonné à la newsletter"
                    ),
                ),
                (
                    "whatsapp_optin",
                    models.BooleanField(default=False, verbose_name="opt-in WhatsApp"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "profil utilisateur",
                "verbose_name_plural": "profils utilisateurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArtistProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artist_name",
                    models.CharField(max_length=200, verbose_name="nom d'artiste"),
                ),
                (
                    "artist_statement",
                    models.TextField(blank=True, verbose_name="déclaration artistique"),
                ),
                (
                    "artistic_style",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="style artistique"
                    ),
                ),
                (
                    "medium",
                    models.CharField(
                        blank=True,
                        help_text="Peinture, Sculpture, Photo, etc.",
                        max_length=200,
                        verbose_name="médium",
                    ),
                ),
                (
                    "birth_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="année de naissance"
                    ),
                ),
                ("education", models.TextField(blank=True, verbose_name="formation")),
                (
                    "awards",
                    models.TextField(blank=True, verbose_name="prix et distinctions"),
                ),
                (
                    "exhibitions",
                    models.TextField(blank=True, verbose_name="expositions"),
                ),
                (
                    "maison_artistes_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="numéro Maison des Artistes",
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        blank=True, max_length=14, verbose_name="numéro SIRET"
                    ),
                ),
                (
                    "represented_by_gallery",
                    models.BooleanField(
                        default=False, verbose_name="représenté par une galerie"
                    ),
                ),
                (
                    "gallery_representation",
                    models.TextField(
                        blank=True, verbose_name="représentation par galeries"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="artiste mis en avant"
                    ),
                ),
                (
                    "featured_since",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="mis en avant depuis"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "profil artiste",
                "verbose_name_plural": "profils artistes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collector_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nom du collectionneur"
                    ),
                ),
                (
                    "collection_focus",
                    models.TextField(blank=True, verbose_name="focus de la collection"),
                ),
                (
                    "collecting_since",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="collectionne depuis"
                    ),
                ),
                (
                    "preferred_styles",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="styles préférés"
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="gamme de budget"
                    ),
                ),
                (
                    "public_collection",
                    models.BooleanField(
                        default=False, verbose_name="collection publique"
                    ),
                ),
                (
                    "show_purchases",
                    models.BooleanField(
                        default=False, verbose_name="afficher les achats"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collector_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "profil collectionneur",
                "verbose_name_plural": "profils collectionneurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GalleryProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gallery_name",
                    models.CharField(max_length=200, verbose_name="nom de la galerie"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "founding_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="année de fondation"
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        blank=True, max_length=14, verbose_name="numéro SIRET"
                    ),
                ),
                (
                    "vat_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="numéro TVA"
                    ),
                ),
                (
                    "cci_member",
                    models.BooleanField(default=False, verbose_name="membre CCI"),
                ),
                (
                    "cci_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="numéro CCI"
                    ),
                ),
                (
                    "has_physical_location",
                    models.BooleanField(
                        default=True, verbose_name="emplacement physique"
                    ),
                ),
                (
                    "opening_hours",
                    models.TextField(blank=True, verbose_name="horaires d'ouverture"),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="spécialisation"
                    ),
                ),
                (
                    "represented_artists_count",
                    models.IntegerField(
                        default=0, verbose_name="nombre d'artistes représentés"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="galerie mise en avant"
                    ),
                ),
                (
                    "featured_since",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="mise en avant depuis"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "profil galerie",
                "verbose_name_plural": "profils galeries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="abonné",
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="suivi",
                    ),
                ),
            ],
            options={
                "verbose_name": "abonnement",
                "verbose_name_plural": "abonnements",
                "ordering": ["-created_at"],
                "unique_together": {("follower", "following")},
            },
        ),
    ]
