# Generated by Django 5.0.1 on 2025-11-06 10:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("ORDER_RECEIVED", "Order Received"),
                            ("ORDER_CONFIRMED", "Order Confirmed"),
                            ("ORDER_READY", "Order Ready"),
                            ("ORDER_DELIVERED", "Order Delivered"),
                            ("ORDER_CANCELLED", "Order Cancelled"),
                            ("RESERVATION_CONFIRMED", "Reservation Confirmed"),
                            ("RESERVATION_REMINDER", "Reservation Reminder"),
                            ("PAYMENT_RECEIVED", "Payment Received"),
                            ("SUBSCRIPTION_EXPIRING", "Subscription Expiring"),
                            ("SYSTEM_ALERT", "System Alert"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("WHATSAPP", "WhatsApp"),
                            ("SMS", "SMS"),
                            ("IN_APP", "In-App"),
                            ("PUSH", "Push Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("READ", "Read"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data for the notification",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "recipient_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("failed_reason", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("ORDER_CONFIRMATION", "Order Confirmation"),
                            ("ORDER_READY", "Order Ready"),
                            ("ORDER_DELIVERED", "Order Delivered"),
                            ("RESERVATION_CONFIRMATION", "Reservation Confirmation"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("WELCOME_EMAIL", "Welcome Email"),
                            ("SUBSCRIPTION_REMINDER", "Subscription Reminder"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=255)),
                ("body_html", models.TextField(help_text="HTML email body")),
                (
                    "body_text",
                    models.TextField(blank=True, help_text="Plain text email body"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_templates",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
                "db_table": "email_templates",
            },
        ),
    ]
