# Generated by Django 5.2.8 on 2025-11-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AICoachConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="New Conversation", max_length=200, verbose_name="title"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "AI coach conversation",
                "verbose_name_plural": "AI coach conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AICoachMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "AI coach message",
                "verbose_name_plural": "AI coach messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("progress", "Progress"),
                            ("suggestion", "Suggestion"),
                            ("pattern", "Pattern"),
                            ("milestone", "Milestone"),
                            ("warning", "Warning"),
                        ],
                        default="suggestion",
                        max_length=20,
                        verbose_name="insight type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("content", models.TextField(verbose_name="content")),
                ("is_read", models.BooleanField(default=False, verbose_name="is read")),
                (
                    "is_helpful",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="is helpful"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "AI insight",
                "verbose_name_plural": "AI insights",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        max_length=20,
                        verbose_name="report type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("content", models.TextField(verbose_name="content")),
                ("summary", models.TextField(blank=True, verbose_name="summary")),
                (
                    "total_actions_completed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total actions completed"
                    ),
                ),
                (
                    "xp_earned",
                    models.PositiveIntegerField(default=0, verbose_name="XP earned"),
                ),
                (
                    "streak_maintained",
                    models.PositiveIntegerField(
                        default=0, verbose_name="streak maintained"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                ("is_read", models.BooleanField(default=False, verbose_name="is read")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "AI report",
                "verbose_name_plural": "AI reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
