# Generated by Django 5.2.8 on 2025-11-05 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_coach", "0001_initial"),
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aicoachconversation",
            name="related_goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="goals.goal",
            ),
        ),
    ]
