# Generated by Django 5.2.8 on 2025-11-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=300, verbose_name="sujet")),
                ("content", models.TextField(verbose_name="contenu")),
                (
                    "html_content",
                    models.TextField(blank=True, verbose_name="contenu HTML"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("SCHEDULED", "Programmé"),
                            ("SENDING", "En cours d'envoi"),
                            ("SENT", "Envoyé"),
                            ("FAILED", "Échec"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="programmé pour"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="envoyé le"
                    ),
                ),
                (
                    "total_recipients",
                    models.IntegerField(
                        default=0, verbose_name="nombre de destinataires"
                    ),
                ),
                ("sent_count", models.IntegerField(default=0, verbose_name="envoyés")),
                (
                    "opened_count",
                    models.IntegerField(default=0, verbose_name="ouverts"),
                ),
                (
                    "clicked_count",
                    models.IntegerField(default=0, verbose_name="cliqués"),
                ),
                (
                    "bounced_count",
                    models.IntegerField(default=0, verbose_name="rejetés"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "campagne email",
                "verbose_name_plural": "campagnes email",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MailingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "liste de diffusion",
                "verbose_name_plural": "listes de diffusion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nom complet"
                    ),
                ),
                (
                    "is_subscribed",
                    models.BooleanField(default=True, verbose_name="abonné"),
                ),
                (
                    "whatsapp_optin",
                    models.BooleanField(default=False, verbose_name="opt-in WhatsApp"),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="numéro WhatsApp"
                    ),
                ),
                (
                    "consent_given",
                    models.BooleanField(
                        default=False, verbose_name="consentement donné"
                    ),
                ),
                (
                    "consent_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date du consentement"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="adresse IP"
                    ),
                ),
                (
                    "subscribed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="abonné le"),
                ),
                (
                    "unsubscribed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="désabonné le"
                    ),
                ),
            ],
            options={
                "verbose_name": "abonné",
                "verbose_name_plural": "abonnés",
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppBroadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(max_length=1600, verbose_name="message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_APPROVAL", "En attente d'approbation"),
                            ("APPROVED", "Approuvé"),
                            ("REJECTED", "Rejeté"),
                            ("SENDING", "En cours d'envoi"),
                            ("SENT", "Envoyé"),
                            ("FAILED", "Échec"),
                        ],
                        default="PENDING_APPROVAL",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="approuvé le"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="raison du rejet"),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="programmé pour"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="envoyé le"
                    ),
                ),
                (
                    "total_recipients",
                    models.IntegerField(
                        default=0, verbose_name="nombre de destinataires"
                    ),
                ),
                ("sent_count", models.IntegerField(default=0, verbose_name="envoyés")),
                (
                    "delivered_count",
                    models.IntegerField(default=0, verbose_name="délivrés"),
                ),
                ("failed_count", models.IntegerField(default=0, verbose_name="échecs")),
                (
                    "cost_per_message",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.05,
                        max_digits=5,
                        verbose_name="coût par message",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="coût total",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "broadcast WhatsApp",
                "verbose_name_plural": "broadcasts WhatsApp",
                "ordering": ["-created_at"],
            },
        ),
    ]
