# Generated by Django 5.2.8 on 2025-11-05 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("communications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mailinglist",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailing_lists",
                to=settings.AUTH_USER_MODEL,
                verbose_name="propriétaire",
            ),
        ),
        migrations.AddField(
            model_name="emailcampaign",
            name="mailing_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="communications.mailinglist",
                verbose_name="liste de diffusion",
            ),
        ),
        migrations.AddField(
            model_name="subscriber",
            name="mailing_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscribers",
                to="communications.mailinglist",
                verbose_name="liste de diffusion",
            ),
        ),
        migrations.AddField(
            model_name="whatsappbroadcast",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_broadcasts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="approuvé par",
            ),
        ),
        migrations.AddField(
            model_name="whatsappbroadcast",
            name="mailing_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whatsapp_broadcasts",
                to="communications.mailinglist",
                verbose_name="liste de diffusion",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subscriber",
            unique_together={("mailing_list", "email")},
        ),
    ]
