# Generated by Django 5.2.8 on 2025-11-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cheer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        choices=[
                            ("🎉", "🎉"),
                            ("💪", "💪"),
                            ("🔥", "🔥"),
                            ("👏", "👏"),
                            ("⭐", "⭐"),
                            ("❤️", "❤️"),
                            ("🚀", "🚀"),
                            ("💯", "💯"),
                        ],
                        default="🎉",
                        max_length=10,
                        verbose_name="emoji",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "cheer",
                "verbose_name_plural": "cheers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "likes_count",
                    models.PositiveIntegerField(default=0, verbose_name="likes count"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="communities/",
                        verbose_name="cover image",
                    ),
                ),
                ("category", models.CharField(max_length=50, verbose_name="category")),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("paid", "Paid"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="privacy",
                    ),
                ),
                (
                    "is_auto_created",
                    models.BooleanField(default=False, verbose_name="is auto created"),
                ),
                (
                    "entry_cost_credits",
                    models.PositiveIntegerField(
                        default=0, verbose_name="entry cost (credits)"
                    ),
                ),
                (
                    "monthly_cost_credits",
                    models.PositiveIntegerField(
                        default=0, verbose_name="monthly cost (credits)"
                    ),
                ),
                (
                    "member_count",
                    models.PositiveIntegerField(default=0, verbose_name="member count"),
                ),
                (
                    "post_count",
                    models.PositiveIntegerField(default=0, verbose_name="post count"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "community",
                "verbose_name_plural": "communities",
                "ordering": ["-member_count", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("moderator", "Moderator"),
                            ("admin", "Admin"),
                        ],
                        default="member",
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="joined at"),
                ),
                (
                    "last_payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last payment date"
                    ),
                ),
            ],
            options={
                "verbose_name": "community membership",
                "verbose_name_plural": "community memberships",
                "ordering": ["-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("comment", "Comment"),
                            ("cheer", "Cheer"),
                            ("follow", "Follow"),
                            ("milestone", "Milestone"),
                            ("badge", "Badge"),
                            ("quest_complete", "Quest Complete"),
                            ("friend_request", "Friend Request"),
                            ("community_invite", "Community Invite"),
                        ],
                        max_length=30,
                        verbose_name="notification type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "related_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                ("read", models.BooleanField(default=False, verbose_name="read")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("goal_share", "Goal Share"),
                            ("achievement", "Achievement"),
                            ("question", "Question"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="post type",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "likes_count",
                    models.PositiveIntegerField(default=0, verbose_name="likes count"),
                ),
                (
                    "comments_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="comments count"
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="is pinned"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "post",
                "verbose_name_plural": "posts",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
    ]
