# Generated by Django 5.2.8 on 2025-11-05 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("community", "0001_initial"),
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cheer",
            name="action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cheers",
                to="goals.action",
            ),
        ),
    ]
