# Generated by Django 5.2.8 on 2025-11-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="titre")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PHYSICAL", "Physique"),
                            ("VIRTUAL", "Virtuel"),
                            ("HYBRID", "Hybride"),
                        ],
                        max_length=50,
                        verbose_name="type d'événement",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="date de début")),
                ("end_date", models.DateTimeField(verbose_name="date de fin")),
                (
                    "location",
                    models.CharField(blank=True, max_length=300, verbose_name="lieu"),
                ),
                (
                    "virtual_link",
                    models.URLField(blank=True, verbose_name="lien virtuel"),
                ),
                (
                    "max_attendees",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="nombre max de participants"
                    ),
                ),
                ("is_free", models.BooleanField(default=True, verbose_name="gratuit")),
                (
                    "ticket_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="prix du billet",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
            ],
            options={
                "verbose_name": "événement",
                "verbose_name_plural": "événements",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="inscrit le"),
                ),
                (
                    "attended",
                    models.BooleanField(default=False, verbose_name="a participé"),
                ),
            ],
            options={
                "verbose_name": "inscription à un événement",
                "verbose_name_plural": "inscriptions à des événements",
                "ordering": ["-registered_at"],
            },
        ),
    ]
