# Generated by Django 5.0.1 on 2025-11-05 12:51

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlineFormation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", ckeditor.fields.RichTextField()),
                ("short_description", models.TextField(max_length=500)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("all", "All Levels"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="online_formations/"
                    ),
                ),
                ("promo_video_url", models.URLField(blank=True)),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("credit", "Credit-based"),
                            ("subscription", "Subscription Only"),
                        ],
                        default="credit",
                        max_length=20,
                    ),
                ),
                (
                    "credit_cost",
                    models.IntegerField(
                        default=0, help_text="Credits required to access"
                    ),
                ),
                (
                    "module_access_type",
                    models.CharField(
                        choices=[
                            ("sequential", "Sequential - Must complete in order"),
                            ("flexible", "Flexible - Access any module"),
                        ],
                        default="flexible",
                        max_length=20,
                    ),
                ),
                (
                    "platform_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        help_text="Platform commission percentage (default from settings)",
                        max_digits=5,
                    ),
                ),
                ("total_enrolled", models.IntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                (
                    "total_completion_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="online_formations",
                        to="formations.category",
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_formations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnlineFormationEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credits_paid", models.IntegerField(default=0)),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "progress_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                ("completed", models.BooleanField(default=False)),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                ("certificate_issued", models.BooleanField(default=False)),
                ("certificate_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "online_formation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="formations.onlineformation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "online_formation")},
            },
        ),
        migrations.CreateModel(
            name="OnlineFormationModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", ckeditor.fields.RichTextField()),
                ("order", models.IntegerField(default=0)),
                (
                    "requires_previous_module",
                    models.BooleanField(
                        default=True, help_text="Must complete previous module first"
                    ),
                ),
                ("estimated_duration_minutes", models.IntegerField(default=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "online_formation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="formations.onlineformation",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("online_formation", "order")},
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", ckeditor.fields.RichTextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("article", "Article/Text"),
                            ("pdf", "PDF Document"),
                            ("quiz", "Quiz"),
                            ("assignment", "Assignment"),
                            ("live", "Live Session"),
                            ("external", "External Link"),
                        ],
                        default="article",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    ckeditor.fields.RichTextField(
                        blank=True, help_text="For article-type lessons"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, help_text="YouTube, Vimeo, etc."),
                ),
                ("video_duration_minutes", models.IntegerField(default=0)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="lessons/pdfs/"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="lessons/attachments/"
                    ),
                ),
                ("external_url", models.URLField(blank=True)),
                (
                    "is_downloadable",
                    models.BooleanField(
                        default=False, help_text="Allow downloading attachments"
                    ),
                ),
                (
                    "is_preview",
                    models.BooleanField(default=False, help_text="Free preview lesson"),
                ),
                ("requires_previous_lesson", models.BooleanField(default=True)),
                ("estimated_duration_minutes", models.IntegerField(default=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="formations.onlineformationmodule",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("module", "order")},
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", ckeditor.fields.RichTextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private - Only Me"),
                            ("public", "Public - Anyone"),
                            ("formation", "Formation Subscribers Only"),
                            ("enrolled", "My Students Only"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "passing_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=70.0,
                        help_text="Percentage required to pass",
                        max_digits=5,
                    ),
                ),
                (
                    "time_limit_minutes",
                    models.IntegerField(default=0, help_text="0 = No time limit"),
                ),
                (
                    "max_attempts",
                    models.IntegerField(default=0, help_text="0 = Unlimited attempts"),
                ),
                (
                    "show_correct_answers",
                    models.BooleanField(
                        default=True, help_text="Show correct answers after completion"
                    ),
                ),
                ("randomize_questions", models.BooleanField(default=False)),
                ("randomize_answers", models.BooleanField(default=True)),
                ("total_attempts", models.IntegerField(default=0)),
                (
                    "average_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_quizzes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Link to specific lesson",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quizzes",
                        to="formations.lesson",
                    ),
                ),
                (
                    "online_formation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Link to online formation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quizzes",
                        to="formations.onlineformation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quizzes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "max_score",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("passed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("time_taken_minutes", models.IntegerField(default=0)),
                ("attempt_number", models.IntegerField(default=1)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="formations.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", ckeditor.fields.RichTextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Choice"),
                            ("multiple", "Multiple Choice"),
                            ("true_false", "True/False"),
                        ],
                        default="single",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="quiz_questions/"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="Optional video for question"
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "points",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                (
                    "explanation",
                    ckeditor.fields.RichTextField(
                        blank=True, help_text="Explanation shown after answering"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="formations.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="formations.quizquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuizResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "points_earned",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="formations.quizattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formations.quizquestion",
                    ),
                ),
                (
                    "selected_answers",
                    models.ManyToManyField(
                        related_name="user_responses", to="formations.quizanswer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=False)),
                ("marked_as_studied", models.BooleanField(default=False)),
                ("time_spent_minutes", models.IntegerField(default=0)),
                (
                    "completion_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="formations.lesson",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to="formations.onlineformationenrollment",
                    ),
                ),
            ],
            options={
                "ordering": ["lesson__order"],
                "unique_together": {("enrollment", "lesson")},
            },
        ),
    ]
