# Generated by Django 5.0.1 on 2025-11-05 12:54

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formations", "0002_onlineformation_onlineformationenrollment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("completion", "Certificate of Completion"),
                            ("achievement", "Certificate of Achievement"),
                            ("excellence", "Certificate of Excellence"),
                            ("participation", "Certificate of Participation"),
                        ],
                        default="completion",
                        max_length=20,
                    ),
                ),
                (
                    "verification_code",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "grade",
                    models.CharField(
                        blank=True, help_text="A+, A, B+, etc.", max_length=10
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "skills",
                    models.TextField(blank=True, help_text="Comma-separated skills"),
                ),
                (
                    "certificate_pdf",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                ("is_verified", models.BooleanField(default=True)),
                ("verification_url", models.URLField(blank=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Null = never expires", null=True
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Show on public profile"
                    ),
                ),
                ("share_count", models.IntegerField(default=0)),
                ("view_count", models.IntegerField(default=0)),
                (
                    "formation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="formations.formation",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "online_formation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="formations.onlineformation",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="formations.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="CertificateVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verified_by_ip", models.GenericIPAddressField()),
                ("verified_at", models.DateTimeField(auto_now_add=True)),
                ("verifier_email", models.EmailField(blank=True, max_length=254)),
                ("verifier_organization", models.CharField(blank=True, max_length=200)),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="formations.certificate",
                    ),
                ),
            ],
            options={
                "ordering": ["-verified_at"],
            },
        ),
        migrations.CreateModel(
            name="LiveStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", ckeditor.fields.RichTextField()),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="livestreams/"),
                ),
                (
                    "stream_url",
                    models.URLField(blank=True, help_text="RTMP or HLS stream URL"),
                ),
                ("stream_key", models.CharField(blank=True, max_length=200)),
                ("chat_enabled", models.BooleanField(default=True)),
                ("recording_enabled", models.BooleanField(default=True)),
                (
                    "recording_url",
                    models.URLField(blank=True, help_text="Recording playback URL"),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("requires_enrollment", models.BooleanField(default=False)),
                (
                    "credit_cost",
                    models.IntegerField(default=0, help_text="Credits to attend"),
                ),
                ("max_viewers", models.IntegerField(default=1000)),
                ("scheduled_start", models.DateTimeField()),
                ("scheduled_end", models.DateTimeField()),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live Now"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("current_viewers", models.IntegerField(default=0)),
                ("peak_viewers", models.IntegerField(default=0)),
                ("total_views", models.IntegerField(default=0)),
                ("allow_questions", models.BooleanField(default=True)),
                ("allow_polls", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "co_hosts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="co_hosted_streams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_streams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="live_streams",
                        to="formations.lesson",
                    ),
                ),
                (
                    "online_formation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="live_streams",
                        to="formations.onlineformation",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_start"],
            },
        ),
        migrations.CreateModel(
            name="LiveStreamMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("chat", "Chat Message"),
                            ("question", "Question"),
                            ("announcement", "Announcement"),
                            ("poll", "Poll"),
                        ],
                        default="chat",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_answered", models.BooleanField(default=False)),
                (
                    "reactions",
                    models.JSONField(default=dict, help_text="{'like': 5, 'love': 2}"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answered_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="formations.livestream",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stream_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("all", "All Levels"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "preferred_delivery",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("in_person", "In Person"),
                            ("remote", "Remote/Online"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                ("preferred_language", models.CharField(default="fr", max_length=10)),
                ("learning_goals", models.TextField(blank=True)),
                ("weekly_learning_hours", models.IntegerField(default=5)),
                ("email_recommendations", models.BooleanField(default=True)),
                (
                    "recommendation_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "favorite_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favorited_by",
                        to="formations.category",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("popular", "Popular Right Now"),
                            ("trending", "Trending in Your Area"),
                            ("similar", "Similar to What You Viewed"),
                            ("category", "Based on Your Interests"),
                            ("completion", "Continue Your Learning"),
                            ("level", "Matches Your Level"),
                            ("coach", "From Coaches You Follow"),
                            ("ai", "AI Personalized Pick"),
                        ],
                        default="ai",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.5,
                        help_text="0-1 confidence",
                        max_digits=5,
                    ),
                ),
                ("shown", models.BooleanField(default=False)),
                ("clicked", models.BooleanField(default=False)),
                ("enrolled", models.BooleanField(default=False)),
                ("shown_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("model_version", models.CharField(default="v1.0", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Recommendation expires after 7 days"
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formations.formation",
                    ),
                ),
                (
                    "online_formation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formations.onlineformation",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formations.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence_score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "shown", "expires_at"],
                        name="formations__user_id_5fa907_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LiveStreamAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("watch_duration_minutes", models.IntegerField(default=0)),
                ("asked_questions", models.IntegerField(default=0)),
                ("reactions_sent", models.IntegerField(default=0)),
                ("eligible_for_certificate", models.BooleanField(default=False)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="formations.livestream",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stream_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-joined_at"],
                "unique_together": {("stream", "user")},
            },
        ),
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "Viewed"),
                            ("click", "Clicked"),
                            ("enroll", "Enrolled"),
                            ("complete", "Completed"),
                            ("rate", "Rated"),
                            ("share", "Shared"),
                            ("bookmark", "Bookmarked"),
                            ("search", "Searched"),
                        ],
                        max_length=20,
                    ),
                ),
                ("search_query", models.CharField(blank=True, max_length=200)),
                (
                    "duration_seconds",
                    models.IntegerField(default=0, help_text="Time spent on page"),
                ),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formations.category",
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formations.formation",
                    ),
                ),
                (
                    "online_formation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formations.onlineformation",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formations.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "interaction_type"],
                        name="formations__user_id_980cad_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="formations__created_828d4a_idx"
                    ),
                ],
            },
        ),
    ]
