# Generated by Django 5.2.8 on 2025-11-05 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artworks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConseilMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="membre depuis"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                ("bio", models.TextField(blank=True, verbose_name="biographie")),
            ],
            options={
                "verbose_name": "membre du conseil",
                "verbose_name_plural": "membres du conseil",
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="ArtworkVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote_date",
                    models.DateField(auto_now_add=True, verbose_name="date du vote"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="commentaire")),
                (
                    "artwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conseil_votes",
                        to="artworks.artwork",
                        verbose_name="œuvre",
                    ),
                ),
            ],
            options={
                "verbose_name": "vote",
                "verbose_name_plural": "votes",
                "ordering": ["-vote_date"],
            },
        ),
    ]
