# Generated by Django 5.2.8 on 2025-11-05 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conseil", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conseilmember",
            name="invited_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conseil_invitations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="invité par",
            ),
        ),
        migrations.AddField(
            model_name="conseilmember",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conseil_membership",
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="artworkvote",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="conseil.conseilmember",
                verbose_name="membre",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="artworkvote",
            unique_together={("artwork", "member", "vote_date")},
        ),
    ]
