# Generated by Django 5.0.1 on 2025-11-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attended", models.BooleanField(default=False)),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("payment_pending", "Payment Pending"),
                            ("payment_received", "Payment Received"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("booking_code", models.CharField(max_length=20, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="MAD", max_length=3)),
                ("payment_instructions_sent", models.BooleanField(default=False)),
                (
                    "payment_instructions_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "user_notes",
                    models.TextField(blank=True, help_text="Notes from the user"),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Internal notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("confirmation", "Booking Confirmation"),
                            ("payment_instructions", "Payment Instructions"),
                            ("payment_received", "Payment Received"),
                            ("reminder", "Reminder"),
                            ("cancellation", "Cancellation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
    ]
