# Generated by Django 5.2.8 on 2025-11-05 19:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="domaine"
                    ),
                ),
                (
                    "domain_type",
                    models.CharField(
                        choices=[
                            ("SUBDOMAIN", "Sous-domaine (gratuit)"),
                            ("CUSTOM", "Domaine personnalisé (payant)"),
                        ],
                        default="SUBDOMAIN",
                        max_length=20,
                        verbose_name="type de domaine",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("ACTIVE", "Actif"),
                            ("SUSPENDED", "Suspendu"),
                            ("EXPIRED", "Expiré"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "ssl_enabled",
                    models.BooleanField(default=False, verbose_name="SSL activé"),
                ),
                (
                    "ssl_issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="SSL émis le"
                    ),
                ),
                (
                    "is_trial",
                    models.BooleanField(
                        default=True, verbose_name="en période d'essai"
                    ),
                ),
                (
                    "trial_ends",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fin de l'essai"
                    ),
                ),
                (
                    "subscription_active",
                    models.BooleanField(default=False, verbose_name="abonnement actif"),
                ),
                (
                    "custom_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="domains/logos/",
                        verbose_name="logo personnalisé",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#000000", max_length=7, verbose_name="couleur primaire"
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#D4AF37",
                        max_length=7,
                        verbose_name="couleur secondaire",
                    ),
                ),
                (
                    "show_jolitableau_branding",
                    models.BooleanField(
                        default=True, verbose_name="afficher la marque JoliTableau"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="titre meta"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="description meta"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="activé le"
                    ),
                ),
            ],
            options={
                "verbose_name": "domaine personnalisé",
                "verbose_name_plural": "domaines personnalisés",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nom complet"
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "English"),
                            ("es", "Español"),
                        ],
                        default="fr",
                        max_length=5,
                        verbose_name="langue préférée",
                    ),
                ),
                (
                    "interested_in_artists",
                    models.BooleanField(
                        default=True, verbose_name="intéressé par les artistes"
                    ),
                ),
                (
                    "interested_in_galleries",
                    models.BooleanField(
                        default=True, verbose_name="intéressé par les galeries"
                    ),
                ),
                (
                    "interested_in_events",
                    models.BooleanField(
                        default=True, verbose_name="intéressé par les événements"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "subscribed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="abonné le"),
                ),
                (
                    "unsubscribed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="désabonné le"
                    ),
                ),
                (
                    "consent_given",
                    models.BooleanField(
                        default=True, verbose_name="consentement donné"
                    ),
                ),
                (
                    "consent_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date du consentement"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="adresse IP"
                    ),
                ),
            ],
            options={
                "verbose_name": "abonné newsletter",
                "verbose_name_plural": "abonnés newsletter",
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "qr_type",
                    models.CharField(
                        choices=[
                            ("ARTWORK", "Œuvre"),
                            ("GALLERY", "Galerie"),
                            ("EXHIBITION", "Exposition"),
                            ("PROFILE", "Profil"),
                            ("EVENT", "Événement"),
                        ],
                        max_length=20,
                        verbose_name="type de QR code",
                    ),
                ),
                (
                    "target_url",
                    models.URLField(max_length=500, verbose_name="URL cible"),
                ),
                (
                    "short_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="code court"
                    ),
                ),
                (
                    "image_png",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qrcodes/png/",
                        verbose_name="image PNG",
                    ),
                ),
                (
                    "image_svg",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="qrcodes/svg/",
                        verbose_name="image SVG",
                    ),
                ),
                (
                    "foreground_color",
                    models.CharField(
                        default="#000000",
                        max_length=7,
                        verbose_name="couleur avant-plan",
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#FFFFFF",
                        max_length=7,
                        verbose_name="couleur arrière-plan",
                    ),
                ),
                (
                    "logo_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qrcodes/logos/",
                        verbose_name="logo central",
                    ),
                ),
                (
                    "scan_count",
                    models.IntegerField(default=0, verbose_name="nombre de scans"),
                ),
                (
                    "last_scanned",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dernier scan"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
            ],
            options={
                "verbose_name": "QR code",
                "verbose_name_plural": "QR codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="JoliTableau",
                        max_length=100,
                        verbose_name="nom du site",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="La galerie d'art en ligne",
                        max_length=200,
                        verbose_name="slogan",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="contact@jolitableau.com",
                        max_length=254,
                        verbose_name="email de contact",
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        default="support@jolitableau.com",
                        max_length=254,
                        verbose_name="email support",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="téléphone"
                    ),
                ),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("twitter_url", models.URLField(blank=True, verbose_name="Twitter/X")),
                ("linkedin_url", models.URLField(blank=True, verbose_name="LinkedIn")),
                (
                    "enable_marketplace",
                    models.BooleanField(
                        default=True, verbose_name="activer marketplace"
                    ),
                ),
                (
                    "enable_auctions",
                    models.BooleanField(default=True, verbose_name="activer enchères"),
                ),
                (
                    "enable_custom_domains",
                    models.BooleanField(
                        default=True, verbose_name="activer domaines personnalisés"
                    ),
                ),
                (
                    "enable_whatsapp_broadcast",
                    models.BooleanField(
                        default=True, verbose_name="activer WhatsApp broadcast"
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(default=False, verbose_name="mode maintenance"),
                ),
                (
                    "domain_monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=9.99,
                        max_digits=6,
                        verbose_name="prix domaine mensuel",
                    ),
                ),
                (
                    "boost_monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=4.99,
                        max_digits=6,
                        verbose_name="prix boost mensuel",
                    ),
                ),
                (
                    "whatsapp_message_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.05,
                        max_digits=5,
                        verbose_name="prix message WhatsApp",
                    ),
                ),
                (
                    "fair_listing_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=49.0,
                        max_digits=6,
                        verbose_name="prix listing foire",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Pourcentage de commission sur les ventes",
                        max_digits=4,
                        verbose_name="taux de commission",
                    ),
                ),
                (
                    "conseil_max_members",
                    models.IntegerField(default=20, verbose_name="max membres conseil"),
                ),
                (
                    "conseil_voting_enabled",
                    models.BooleanField(
                        default=True, verbose_name="votes conseil activés"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "paramètres du site",
                "verbose_name_plural": "paramètres du site",
            },
        ),
    ]
