# Generated by Django 5.2.8 on 2025-11-05 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customdomain",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_domains",
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qr_codes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="propriétaire",
            ),
        ),
        migrations.AddIndex(
            model_name="qrcode",
            index=models.Index(
                fields=["short_code"], name="core_qrcode_short_c_709fac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qrcode",
            index=models.Index(fields=["uuid"], name="core_qrcode_uuid_2ff219_idx"),
        ),
    ]
