# Generated by Django 5.2.8 on 2025-11-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="titre")),
                (
                    "slug",
                    models.SlugField(max_length=350, unique=True, verbose_name="slug"),
                ),
                (
                    "description_fr",
                    models.TextField(blank=True, verbose_name="description (français)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="description (anglais)"),
                ),
                (
                    "description_es",
                    models.TextField(blank=True, verbose_name="description (espagnol)"),
                ),
                (
                    "medium",
                    models.CharField(
                        help_text="Peinture à l'huile, Sculpture bronze, etc.",
                        max_length=200,
                        verbose_name="médium",
                    ),
                ),
                (
                    "style",
                    models.CharField(blank=True, max_length=100, verbose_name="style"),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="largeur (cm)",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="hauteur (cm)",
                    ),
                ),
                (
                    "depth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="profondeur (cm)",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="poids (kg)",
                    ),
                ),
                (
                    "year_created",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="année de création"
                    ),
                ),
                (
                    "date_created",
                    models.DateField(
                        blank=True, null=True, verbose_name="date de création"
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        upload_to="artworks/", verbose_name="image principale"
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="artworks/",
                        verbose_name="image 2",
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="artworks/",
                        verbose_name="image 3",
                    ),
                ),
                (
                    "image_4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="artworks/",
                        verbose_name="image 4",
                    ),
                ),
                (
                    "video_360",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="artworks/360/",
                        verbose_name="vidéo 360°",
                    ),
                ),
                (
                    "ar_model",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="artworks/ar/",
                        verbose_name="modèle AR",
                    ),
                ),
                (
                    "is_for_sale",
                    models.BooleanField(default=True, verbose_name="à vendre"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="prix",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="devise"
                    ),
                ),
                (
                    "price_on_request",
                    models.BooleanField(default=False, verbose_name="prix sur demande"),
                ),
                (
                    "is_auction",
                    models.BooleanField(default=False, verbose_name="aux enchères"),
                ),
                (
                    "starting_bid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="enchère de départ",
                    ),
                ),
                (
                    "is_unique",
                    models.BooleanField(default=True, verbose_name="pièce unique"),
                ),
                (
                    "edition_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="numéro d'édition"
                    ),
                ),
                (
                    "edition_total",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="total édition"
                    ),
                ),
                (
                    "has_certificate",
                    models.BooleanField(
                        default=False, verbose_name="certificat d'authenticité"
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="numéro de certificat"
                    ),
                ),
                ("is_signed", models.BooleanField(default=False, verbose_name="signé")),
                (
                    "signature_location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="emplacement signature"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("PUBLISHED", "Publié"),
                            ("SOLD", "Vendu"),
                            ("ARCHIVED", "Archivé"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="mis en avant"),
                ),
                (
                    "featured_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="mis en avant jusqu'au"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Séparés par des virgules",
                        max_length=500,
                        verbose_name="tags",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="mots-clés meta"
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(default=0, verbose_name="nombre de vues"),
                ),
                (
                    "favorite_count",
                    models.IntegerField(default=0, verbose_name="favoris"),
                ),
                (
                    "share_count",
                    models.IntegerField(default=0, verbose_name="partages"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="publié le"
                    ),
                ),
                (
                    "sold_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="vendu le"
                    ),
                ),
            ],
            options={
                "verbose_name": "œuvre",
                "verbose_name_plural": "œuvres",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArtworkImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="artworks/gallery/", verbose_name="image"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="légende"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ordre")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
            ],
            options={
                "verbose_name": "image d'œuvre",
                "verbose_name_plural": "images d'œuvre",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(max_length=100, verbose_name="nom (français)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="nom (anglais)"),
                ),
                (
                    "name_es",
                    models.CharField(max_length=100, verbose_name="nom (espagnol)"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="icône"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
            ],
            options={
                "verbose_name": "catégorie",
                "verbose_name_plural": "catégories",
                "ordering": ["name_fr"],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
            ],
            options={
                "verbose_name": "favori",
                "verbose_name_plural": "favoris",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Provenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateField(verbose_name="date de l'événement")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création"),
                            ("ACQUISITION", "Acquisition"),
                            ("SALE", "Vente"),
                            ("EXHIBITION", "Exposition"),
                            ("RESTORATION", "Restauration"),
                            ("TRANSFER", "Transfert"),
                        ],
                        max_length=50,
                        verbose_name="type d'événement",
                    ),
                ),
                (
                    "from_party",
                    models.CharField(blank=True, max_length=200, verbose_name="de"),
                ),
                (
                    "to_party",
                    models.CharField(blank=True, max_length=200, verbose_name="à"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="lieu"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "documentation",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="provenance/docs/",
                        verbose_name="documentation",
                    ),
                ),
                (
                    "blockchain_verified",
                    models.BooleanField(
                        default=False, verbose_name="vérifié blockchain"
                    ),
                ),
                (
                    "transaction_hash",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="hash de transaction"
                    ),
                ),
                (
                    "nft_token_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="ID token NFT"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "provenance",
                "verbose_name_plural": "provenances",
                "ordering": ["-event_date"],
            },
        ),
    ]
