# Generated by Django 5.2.8 on 2025-11-05 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artworks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artworks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="artiste",
            ),
        ),
        migrations.AddField(
            model_name="artworkimage",
            name="artwork",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_images",
                to="artworks.artwork",
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="artworks",
                to="artworks.category",
                verbose_name="catégorie",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="artwork",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="artworks.artwork",
                verbose_name="œuvre",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="provenance",
            name="artwork",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provenance_records",
                to="artworks.artwork",
                verbose_name="œuvre",
            ),
        ),
        migrations.AddIndex(
            model_name="artwork",
            index=models.Index(fields=["slug"], name="artworks_ar_slug_77d23c_idx"),
        ),
        migrations.AddIndex(
            model_name="artwork",
            index=models.Index(
                fields=["status", "-created_at"], name="artworks_ar_status_5b775d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artwork",
            index=models.Index(
                fields=["is_for_sale", "price"], name="artworks_ar_is_for__d11520_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "artwork")},
        ),
    ]
