# Generated by Django 5.0.1 on 2025-11-05 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("formations", "0002_onlineformation_onlineformationenrollment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, help_text="Has verified badge"),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(
                default=True, help_text="Auto-approved - legacy field"
            ),
        ),
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credit_price_mad",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Price of 1 credit in MAD",
                        max_digits=10,
                    ),
                ),
                (
                    "verification_badge_cost",
                    models.IntegerField(
                        default=100,
                        help_text="Credits required for verification badge application",
                    ),
                ),
                (
                    "featured_formation_cost",
                    models.IntegerField(
                        default=50, help_text="Credits to feature a formation"
                    ),
                ),
                (
                    "premium_listing_cost",
                    models.IntegerField(
                        default=75, help_text="Credits for premium listing"
                    ),
                ),
                (
                    "default_platform_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        help_text="Default platform commission percentage",
                        max_digits=5,
                    ),
                ),
                ("credit_package_small", models.IntegerField(default=10)),
                ("credit_package_small_bonus", models.IntegerField(default=0)),
                ("credit_package_medium", models.IntegerField(default=50)),
                ("credit_package_medium_bonus", models.IntegerField(default=5)),
                ("credit_package_large", models.IntegerField(default=100)),
                ("credit_package_large_bonus", models.IntegerField(default=15)),
                ("credit_package_xl", models.IntegerField(default=500)),
                ("credit_package_xl_bonus", models.IntegerField(default=100)),
                (
                    "min_withdrawal_credits",
                    models.IntegerField(
                        default=1000, help_text="Minimum credits for coach withdrawal"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Platform Settings",
            },
        ),
        migrations.CreateModel(
            name="VerificationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motivation",
                    models.TextField(help_text="Why user wants verification"),
                ),
                (
                    "credentials",
                    models.TextField(
                        blank=True,
                        help_text="Professional credentials, certifications, etc.",
                    ),
                ),
                ("website", models.URLField(blank=True)),
                (
                    "social_proof",
                    models.URLField(blank=True, help_text="LinkedIn, portfolio, etc."),
                ),
                (
                    "id_document",
                    models.FileField(
                        blank=True, null=True, upload_to="verification_docs/"
                    ),
                ),
                (
                    "credential_document",
                    models.FileField(
                        blank=True, null=True, upload_to="verification_docs/"
                    ),
                ),
                (
                    "credits_paid",
                    models.IntegerField(
                        default=0, help_text="Credits paid for verification request"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Credit Purchase"),
                            ("spent", "Credits Spent"),
                            ("earned", "Credits Earned"),
                            ("refund", "Credit Refund"),
                            ("bonus", "Bonus Credits"),
                            ("admin_adjustment", "Admin Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Positive for credits added, negative for spent"
                    ),
                ),
                (
                    "balance_after",
                    models.IntegerField(
                        help_text="User's credit balance after this transaction"
                    ),
                ),
                ("description", models.TextField()),
                (
                    "payment_amount_mad",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount paid in MAD for credit purchase",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "payment_proof",
                    models.FileField(
                        blank=True, null=True, upload_to="credit_payments/"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "online_formation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="formations.onlineformation",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verification_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.verificationrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
