# Generated by Django 5.0.1 on 2025-11-06 10:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="menu/categories/"
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_categories",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Category",
                "verbose_name_plural": "Menu Categories",
                "db_table": "menu_categories",
                "ordering": ["display_order", "name"],
                "unique_together": {("restaurant", "name")},
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="menu/items/"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost to make this item",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_popular", models.BooleanField(default=False)),
                (
                    "dietary_type",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("VEGETARIAN", "Vegetarian"),
                            ("VEGAN", "Vegan"),
                            ("GLUTEN_FREE", "Gluten Free"),
                            ("DAIRY_FREE", "Dairy Free"),
                            ("HALAL", "Halal"),
                            ("KOSHER", "Kosher"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                (
                    "spice_level",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("MILD", "Mild"),
                            ("MEDIUM", "Medium"),
                            ("HOT", "Hot"),
                            ("EXTRA_HOT", "Extra Hot"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                (
                    "allergens",
                    models.JSONField(
                        blank=True, default=list, help_text="List of allergens"
                    ),
                ),
                ("calories", models.IntegerField(blank=True, null=True)),
                (
                    "prep_time",
                    models.IntegerField(
                        default=15, help_text="Preparation time in minutes"
                    ),
                ),
                ("track_inventory", models.BooleanField(default=False)),
                ("stock_quantity", models.IntegerField(default=0)),
                ("low_stock_threshold", models.IntegerField(default=5)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menus.menucategory",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Item",
                "verbose_name_plural": "Menu Items",
                "db_table": "menu_items",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItemModifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Size, Toppings, Extras", max_length=100
                    ),
                ),
                (
                    "modifier_type",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single Choice"),
                            ("MULTIPLE", "Multiple Choice"),
                        ],
                        default="SINGLE",
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("min_selections", models.IntegerField(default=0)),
                ("max_selections", models.IntegerField(default=1)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifiers",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Item Modifier",
                "verbose_name_plural": "Menu Item Modifiers",
                "db_table": "menu_item_modifiers",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItemModifierLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifier_links",
                        to="menus.menuitem",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_links",
                        to="menus.menuitemmodifier",
                    ),
                ),
            ],
            options={
                "db_table": "menu_item_modifier_links",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="MenuItemModifierOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Additional price for this option",
                        max_digits=10,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_available", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="menus.menuitemmodifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modifier Option",
                "verbose_name_plural": "Modifier Options",
                "db_table": "menu_item_modifier_options",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItemVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Small, Medium, Large, Chocolate, Vanilla",
                        max_length=100,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="Stock Keeping Unit",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="menus.menuitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Item Variant",
                "verbose_name_plural": "Menu Item Variants",
                "db_table": "menu_item_variants",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["restaurant", "is_available"],
                name="menu_items_restaur_d2ad1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["category"], name="menu_items_categor_de3aed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["is_featured"], name="menu_items_is_feat_1963a3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="menuitemmodifierlink",
            unique_together={("menu_item", "modifier")},
        ),
        migrations.AlterUniqueTogether(
            name="menuitemvariant",
            unique_together={("menu_item", "name")},
        ),
    ]
