from django.core.management.base import BaseCommand
from django.utils.text import slugify
from gamification.models import Badge


class Command(BaseCommand):
    help = "Crée 130 badges supplémentaires avec une touche marocaine"

    def handle(self, *args, **kwargs):
        self.stdout.write("Création de 130 badges marocains supplémentaires...\n")

        badges = [
            # MOROCCAN CITIES & REGIONS (20 badges)
            {
                "name": "Casablancais",
                "category": "expert",
                "description": "Suivre 10 formations à Casablanca",
                "icon": "🌆",
                "points": 200,
            },
            {
                "name": "Rbati",
                "category": "expert",
                "description": "Suivre une formation à Rabat",
                "icon": "🏛️",
                "points": 100,
            },
            {
                "name": "Marrakchi",
                "category": "expert",
                "description": "Suivre une formation à Marrakech",
                "icon": "🕌",
                "points": 100,
            },
            {
                "name": "Tangérois",
                "category": "expert",
                "description": "Formation à Tanger",
                "icon": "🌊",
                "points": 100,
            },
            {
                "name": "Fassi",
                "category": "expert",
                "description": "Formation à Fès",
                "icon": "📚",
                "points": 100,
            },
            {
                "name": "Jdidi",
                "category": "expert",
                "description": "Formation à El Jadida",
                "icon": "🏖️",
                "points": 100,
            },
            {
                "name": "Agadiri",
                "category": "expert",
                "description": "Formation à Agadir",
                "icon": "🌴",
                "points": 100,
            },
            {
                "name": "Saharien",
                "category": "expert",
                "description": "Formation dans le sud marocain",
                "icon": "🐪",
                "points": 150,
            },
            {
                "name": "Montagnard",
                "category": "expert",
                "description": "Formation dans l'Atlas",
                "icon": "⛰️",
                "points": 150,
            },
            {
                "name": "Oujdi",
                "category": "expert",
                "description": "Formation à Oujda",
                "icon": "🌅",
                "points": 100,
            },
            {
                "name": "Tetouani",
                "category": "expert",
                "description": "Formation à Tétouan",
                "icon": "🏰",
                "points": 100,
            },
            {
                "name": "Meknassi",
                "category": "expert",
                "description": "Formation à Meknès",
                "icon": "🚪",
                "points": 100,
            },
            {
                "name": "Essaouiri",
                "category": "expert",
                "description": "Formation à Essaouira",
                "icon": "🎸",
                "points": 100,
            },
            {
                "name": "Tour du Maroc",
                "category": "achievement",
                "description": "Formations dans 5 villes différentes",
                "icon": "🗺️",
                "points": 500,
            },
            {
                "name": "Grand Voyageur",
                "category": "achievement",
                "description": "Formations dans 10 villes",
                "icon": "✈️",
                "points": 1000,
            },
            {
                "name": "Nomade Moderne",
                "category": "participation",
                "description": "Alterner formations en ligne et présentiel",
                "icon": "💼",
                "points": 200,
            },
            {
                "name": "Côte Atlantique",
                "category": "expert",
                "description": "Formations dans 3 villes côtières",
                "icon": "🌊",
                "points": 300,
            },
            {
                "name": "Villes Impériales",
                "category": "expert",
                "description": "Formations dans les 4 villes impériales",
                "icon": "👑",
                "points": 600,
            },
            {
                "name": "Nord du Maroc",
                "category": "expert",
                "description": "Formations dans le nord",
                "icon": "🏔️",
                "points": 250,
            },
            {
                "name": "Sud du Maroc",
                "category": "expert",
                "description": "Formations dans le sud",
                "icon": "🏜️",
                "points": 250,
            },
            # MOROCCAN CUISINE (15 badges)
            {
                "name": "Amateur de Couscous",
                "category": "social",
                "description": "Participer à un atelier culinaire couscous",
                "icon": "🍲",
                "points": 100,
            },
            {
                "name": "Maître Tajine",
                "category": "expert",
                "description": "Formation cuisine marocaine complète",
                "icon": "🥘",
                "points": 300,
            },
            {
                "name": "Pâtissier Marocain",
                "category": "expert",
                "description": "Formation pâtisserie marocaine",
                "icon": "🥮",
                "points": 250,
            },
            {
                "name": "Thé à la Menthe",
                "category": "beginner",
                "description": "Assister à 5 formations matinales",
                "icon": "🍵",
                "points": 50,
            },
            {
                "name": "Chef du Ramadan",
                "category": "special",
                "description": "Formation cuisine pendant Ramadan",
                "icon": "🌙",
                "points": 200,
            },
            {
                "name": "Pain Marocain",
                "category": "participation",
                "description": "Atelier boulangerie traditionnelle",
                "icon": "🥖",
                "points": 100,
            },
            {
                "name": "Msemen Master",
                "category": "expert",
                "description": "Maîtriser la cuisine du petit-déjeuner",
                "icon": "🥞",
                "points": 150,
            },
            {
                "name": "Harira Expert",
                "category": "participation",
                "description": "Cours de cuisine traditionnelle",
                "icon": "🍜",
                "points": 100,
            },
            {
                "name": "Sellou Artisan",
                "category": "expert",
                "description": "Formation pâtisserie festive",
                "icon": "🍪",
                "points": 150,
            },
            {
                "name": "Bastilla Chef",
                "category": "expert",
                "description": "Maîtriser les plats sophistiqués",
                "icon": "🥧",
                "points": 200,
            },
            {
                "name": "Zaalouk Specialist",
                "category": "participation",
                "description": "Formation salades marocaines",
                "icon": "🥗",
                "points": 100,
            },
            {
                "name": "Kefta Master",
                "category": "participation",
                "description": "Formation viandes et grillades",
                "icon": "🍖",
                "points": 150,
            },
            {
                "name": "Chebakia Pro",
                "category": "expert",
                "description": "Pâtisserie traditionnelle avancée",
                "icon": "🍯",
                "points": 200,
            },
            {
                "name": "Cuisine du Terroir",
                "category": "achievement",
                "description": "Compléter 5 ateliers culinaires",
                "icon": "👨‍🍳",
                "points": 500,
            },
            {
                "name": "Gastronome Marocain",
                "category": "expert",
                "description": "Expert en cuisine marocaine",
                "icon": "🎖️",
                "points": 1000,
            },
            # MOROCCAN CULTURE & TRADITIONS (20 badges)
            {
                "name": "Caftan Élégance",
                "category": "social",
                "description": "Formation couture traditionnelle",
                "icon": "👗",
                "points": 150,
            },
            {
                "name": "Jelaba Moderne",
                "category": "participation",
                "description": "Atelier mode marocaine",
                "icon": "🧥",
                "points": 100,
            },
            {
                "name": "Babouche Artisan",
                "category": "expert",
                "description": "Formation artisanat cuir",
                "icon": "👞",
                "points": 200,
            },
            {
                "name": "Zellij Master",
                "category": "expert",
                "description": "Formation mosaïque marocaine",
                "icon": "🎨",
                "points": 300,
            },
            {
                "name": "Tapis Berbère",
                "category": "expert",
                "description": "Tissage traditionnel",
                "icon": "🧵",
                "points": 250,
            },
            {
                "name": "Calligraphie Arabe",
                "category": "expert",
                "description": "Art de la calligraphie",
                "icon": "✍️",
                "points": 200,
            },
            {
                "name": "Musique Andalouse",
                "category": "participation",
                "description": "Formation musique traditionnelle",
                "icon": "🎵",
                "points": 150,
            },
            {
                "name": "Gnaoua Rhythm",
                "category": "participation",
                "description": "Découverte musique Gnaoua",
                "icon": "🥁",
                "points": 150,
            },
            {
                "name": "Conteur du Souk",
                "category": "social",
                "description": "Formation storytelling marocain",
                "icon": "📖",
                "points": 100,
            },
            {
                "name": "Henné Artist",
                "category": "expert",
                "description": "Formation art du henné",
                "icon": "🎨",
                "points": 150,
            },
            {
                "name": "Poterie de Safi",
                "category": "expert",
                "description": "Poterie traditionnelle",
                "icon": "🏺",
                "points": 200,
            },
            {
                "name": "Argent de Tiznit",
                "category": "expert",
                "description": "Bijouterie traditionnelle",
                "icon": "💍",
                "points": 250,
            },
            {
                "name": "Cuir de Fès",
                "category": "expert",
                "description": "Tannerie et maroquinerie",
                "icon": "👜",
                "points": 200,
            },
            {
                "name": "Bois de Thuya",
                "category": "expert",
                "description": "Ébénisterie traditionnelle",
                "icon": "🪵",
                "points": 200,
            },
            {
                "name": "Gardien des Traditions",
                "category": "achievement",
                "description": "10 formations artisanat",
                "icon": "🏛️",
                "points": 800,
            },
            {
                "name": "Maâlem",
                "category": "expert",
                "description": "Maître artisan certifié",
                "icon": "👨‍🎨",
                "points": 1000,
            },
            {
                "name": "UNESCO Heritage",
                "category": "special",
                "description": "Formation patrimoine mondial",
                "icon": "🌍",
                "points": 500,
            },
            {
                "name": "Fantasía Rider",
                "category": "special",
                "description": "Découverte traditions équestres",
                "icon": "🐴",
                "points": 200,
            },
            {
                "name": "Moussem Participant",
                "category": "special",
                "description": "Formation festivals traditionnels",
                "icon": "🎪",
                "points": 150,
            },
            {
                "name": "Ambassadeur Culturel",
                "category": "achievement",
                "description": "Promouvoir la culture marocaine",
                "icon": "🇲🇦",
                "points": 600,
            },
            # MOROCCAN BUSINESS & ENTREPRENEURSHIP (15 badges)
            {
                "name": "Entrepreneur Marocain",
                "category": "achievement",
                "description": "Formation création entreprise au Maroc",
                "icon": "🚀",
                "points": 300,
            },
            {
                "name": "Auto-Entrepreneur",
                "category": "participation",
                "description": "Statut auto-entrepreneur",
                "icon": "💼",
                "points": 200,
            },
            {
                "name": "Export Champion",
                "category": "expert",
                "description": "Formation commerce international",
                "icon": "🌍",
                "points": 400,
            },
            {
                "name": "Startup Casablanca",
                "category": "achievement",
                "description": "Intégrer un incubateur",
                "icon": "🏢",
                "points": 500,
            },
            {
                "name": "Finance Islamique",
                "category": "expert",
                "description": "Certification finance islamique",
                "icon": "🏦",
                "points": 400,
            },
            {
                "name": "Comptable Marocain",
                "category": "expert",
                "description": "Formation comptabilité CGNC",
                "icon": "📊",
                "points": 350,
            },
            {
                "name": "Fiscalité Marocaine",
                "category": "expert",
                "description": "Expert fiscalité",
                "icon": "💰",
                "points": 400,
            },
            {
                "name": "Droit des Affaires",
                "category": "expert",
                "description": "Formation droit marocain",
                "icon": "⚖️",
                "points": 350,
            },
            {
                "name": "SARL Expert",
                "category": "participation",
                "description": "Création SARL au Maroc",
                "icon": "🏛️",
                "points": 200,
            },
            {
                "name": "SA Master",
                "category": "participation",
                "description": "Gestion SA",
                "icon": "🏢",
                "points": 250,
            },
            {
                "name": "Marché Public",
                "category": "expert",
                "description": "Appels d'offres publics",
                "icon": "📑",
                "points": 300,
            },
            {
                "name": "Zones Franches",
                "category": "expert",
                "description": "Opportunités zones franches",
                "icon": "🏗️",
                "points": 300,
            },
            {
                "name": "Made in Morocco",
                "category": "achievement",
                "description": "Promouvoir production locale",
                "icon": "🇲🇦",
                "points": 400,
            },
            {
                "name": "Investisseur Maroc",
                "category": "achievement",
                "description": "Formation investissement",
                "icon": "💎",
                "points": 500,
            },
            {
                "name": "Business Leader",
                "category": "expert",
                "description": "Leader business marocain",
                "icon": "👔",
                "points": 1000,
            },
            # MOROCCAN LANGUAGES (15 badges)
            {
                "name": "Darija Speaker",
                "category": "participation",
                "description": "Formation dialecte marocain",
                "icon": "🗣️",
                "points": 150,
            },
            {
                "name": "Arabe Classique",
                "category": "participation",
                "description": "Cours arabe littéraire",
                "icon": "📚",
                "points": 200,
            },
            {
                "name": "Amazigh Apprenant",
                "category": "participation",
                "description": "Apprendre le berbère",
                "icon": "🏔️",
                "points": 200,
            },
            {
                "name": "Français du Maroc",
                "category": "beginner",
                "description": "Français niveau avancé",
                "icon": "🇫🇷",
                "points": 100,
            },
            {
                "name": "English for Business",
                "category": "participation",
                "description": "Anglais des affaires",
                "icon": "🇬🇧",
                "points": 150,
            },
            {
                "name": "Español Marroquí",
                "category": "participation",
                "description": "Espagnol pour marocains",
                "icon": "🇪🇸",
                "points": 150,
            },
            {
                "name": "Trilingue Marocain",
                "category": "achievement",
                "description": "Maîtriser 3 langues",
                "icon": "🌍",
                "points": 400,
            },
            {
                "name": "Quadrilingue",
                "category": "achievement",
                "description": "Parler 4 langues",
                "icon": "🌎",
                "points": 600,
            },
            {
                "name": "Polyglotte Maroc",
                "category": "expert",
                "description": "5 langues ou plus",
                "icon": "🗺️",
                "points": 1000,
            },
            {
                "name": "Traducteur Pro",
                "category": "expert",
                "description": "Formation traduction",
                "icon": "📝",
                "points": 400,
            },
            {
                "name": "Interprète",
                "category": "expert",
                "description": "Interprétation simultanée",
                "icon": "🎤",
                "points": 500,
            },
            {
                "name": "Prof de Langues",
                "category": "achievement",
                "description": "Enseigner une langue",
                "icon": "👨‍🏫",
                "points": 300,
            },
            {
                "name": "Hassania Speaker",
                "category": "expert",
                "description": "Dialecte hassani",
                "icon": "🐪",
                "points": 200,
            },
            {
                "name": "Rifain Speaker",
                "category": "participation",
                "description": "Dialecte rifain",
                "icon": "⛰️",
                "points": 150,
            },
            {
                "name": "Chelha Speaker",
                "category": "participation",
                "description": "Tachelhit/Soussiya",
                "icon": "🏔️",
                "points": 150,
            },
            # MOROCCAN TECH & INNOVATION (15 badges)
            {
                "name": "Technopark Graduate",
                "category": "achievement",
                "description": "Formation dans un technopark",
                "icon": "🏢",
                "points": 300,
            },
            {
                "name": "UM6P Certified",
                "category": "special",
                "description": "Formation UM6P",
                "icon": "🎓",
                "points": 400,
            },
            {
                "name": "Coding Dojo Maroc",
                "category": "participation",
                "description": "Bootcamp programmation",
                "icon": "💻",
                "points": 200,
            },
            {
                "name": "Fintech Morocco",
                "category": "expert",
                "description": "Innovation financière",
                "icon": "💳",
                "points": 350,
            },
            {
                "name": "E-commerce Maroc",
                "category": "participation",
                "description": "Vente en ligne au Maroc",
                "icon": "🛒",
                "points": 200,
            },
            {
                "name": "Digital Nomad Maroc",
                "category": "achievement",
                "description": "Travail à distance",
                "icon": "🌴",
                "points": 250,
            },
            {
                "name": "Smart City Casa",
                "category": "expert",
                "description": "Technologies urbaines",
                "icon": "🌆",
                "points": 300,
            },
            {
                "name": "Green Tech Maroc",
                "category": "expert",
                "description": "Technologies vertes",
                "icon": "🌱",
                "points": 350,
            },
            {
                "name": "Agritech Pioneer",
                "category": "expert",
                "description": "Agriculture 4.0",
                "icon": "🚜",
                "points": 300,
            },
            {
                "name": "Blockchain Maroc",
                "category": "expert",
                "description": "Blockchain et crypto",
                "icon": "⛓️",
                "points": 400,
            },
            {
                "name": "IoT Morocco",
                "category": "expert",
                "description": "Internet des objets",
                "icon": "📡",
                "points": 350,
            },
            {
                "name": "AI Morocco",
                "category": "expert",
                "description": "Intelligence artificielle",
                "icon": "🤖",
                "points": 500,
            },
            {
                "name": "Cybersécurité Maroc",
                "category": "expert",
                "description": "Sécurité informatique",
                "icon": "🔒",
                "points": 450,
            },
            {
                "name": "Cloud Morocco",
                "category": "expert",
                "description": "Cloud computing",
                "icon": "☁️",
                "points": 350,
            },
            {
                "name": "Tech4Good Maroc",
                "category": "achievement",
                "description": "Tech à impact social",
                "icon": "❤️",
                "points": 400,
            },
            # MOROCCAN SPORTS & WELLNESS (15 badges)
            {
                "name": "Football Fan",
                "category": "social",
                "description": "Formation sport collectif",
                "icon": "⚽",
                "points": 100,
            },
            {
                "name": "Raja Ultras",
                "category": "special",
                "description": "Supporter emblématique",
                "icon": "🦅",
                "points": 150,
            },
            {
                "name": "Wydad Winner",
                "category": "special",
                "description": "Fan Wydad",
                "icon": "🔴",
                "points": 150,
            },
            {
                "name": "Surf Essaouira",
                "category": "participation",
                "description": "Formation surf",
                "icon": "🏄",
                "points": 200,
            },
            {
                "name": "Atlas Trekker",
                "category": "achievement",
                "description": "Randonnée Atlas",
                "icon": "🥾",
                "points": 250,
            },
            {
                "name": "Yoga Marrakech",
                "category": "participation",
                "description": "Retraite yoga",
                "icon": "🧘",
                "points": 150,
            },
            {
                "name": "Hammam Therapy",
                "category": "participation",
                "description": "Formation bien-être",
                "icon": "♨️",
                "points": 100,
            },
            {
                "name": "Argan Specialist",
                "category": "expert",
                "description": "Huile d'argan et cosmétique",
                "icon": "🌰",
                "points": 200,
            },
            {
                "name": "Marathon Casablanca",
                "category": "achievement",
                "description": "Participer au marathon",
                "icon": "🏃",
                "points": 300,
            },
            {
                "name": "Cycliste Maroc",
                "category": "participation",
                "description": "Tour cycliste",
                "icon": "🚴",
                "points": 200,
            },
            {
                "name": "Natation Pro",
                "category": "participation",
                "description": "Formation natation",
                "icon": "🏊",
                "points": 150,
            },
            {
                "name": "Équitation Tbourida",
                "category": "special",
                "description": "Équitation traditionnelle",
                "icon": "🐎",
                "points": 300,
            },
            {
                "name": "Golf Morocco",
                "category": "participation",
                "description": "Golf professionnel",
                "icon": "⛳",
                "points": 250,
            },
            {
                "name": "Fitness Maroc",
                "category": "participation",
                "description": "Coach sportif certifié",
                "icon": "💪",
                "points": 200,
            },
            {
                "name": "Wellness Expert",
                "category": "expert",
                "description": "Expert bien-être",
                "icon": "🌟",
                "points": 400,
            },
            # MOROCCAN HISTORY & HERITAGE (15 badges)
            {
                "name": "Hassan II Scholar",
                "category": "participation",
                "description": "Histoire contemporaine",
                "icon": "📚",
                "points": 150,
            },
            {
                "name": "Mohammed V Legacy",
                "category": "participation",
                "description": "Histoire de l'indépendance",
                "icon": "🎖️",
                "points": 150,
            },
            {
                "name": "Dynastie Alaouite",
                "category": "expert",
                "description": "Histoire des dynasties",
                "icon": "👑",
                "points": 200,
            },
            {
                "name": "Empire Almohade",
                "category": "expert",
                "description": "Histoire médiévale",
                "icon": "🏰",
                "points": 200,
            },
            {
                "name": "Mérinides Scholar",
                "category": "expert",
                "description": "Architecture mérinide",
                "icon": "🕌",
                "points": 200,
            },
            {
                "name": "Volubilis Expert",
                "category": "participation",
                "description": "Archéologie romaine",
                "icon": "🏛️",
                "points": 150,
            },
            {
                "name": "Médina Guardian",
                "category": "achievement",
                "description": "Protection patrimoine",
                "icon": "🏺",
                "points": 300,
            },
            {
                "name": "Qaraouiyine Scholar",
                "category": "special",
                "description": "Plus ancienne université",
                "icon": "📖",
                "points": 400,
            },
            {
                "name": "Hassan II Mosque",
                "category": "beginner",
                "description": "Visite emblématique",
                "icon": "🕌",
                "points": 50,
            },
            {
                "name": "Kasbah Explorer",
                "category": "participation",
                "description": "Découverte kasbahs",
                "icon": "🏜️",
                "points": 150,
            },
            {
                "name": "Medersas Master",
                "category": "expert",
                "description": "Architecture éducative",
                "icon": "🎓",
                "points": 250,
            },
            {
                "name": "Palais Royal",
                "category": "participation",
                "description": "Architecture royale",
                "icon": "🏰",
                "points": 150,
            },
            {
                "name": "Remparts de Marrakech",
                "category": "participation",
                "description": "Fortifications historiques",
                "icon": "🧱",
                "points": 100,
            },
            {
                "name": "Historien Marocain",
                "category": "expert",
                "description": "Expert histoire du Maroc",
                "icon": "📜",
                "points": 600,
            },
            {
                "name": "Patrimoine UNESCO",
                "category": "achievement",
                "description": "Visiter tous les sites UNESCO",
                "icon": "🌍",
                "points": 800,
            },
        ]

        created_count = 0
        for badge_data in badges:
            badge, created = Badge.objects.get_or_create(
                name=badge_data["name"],
                defaults={
                    "slug": slugify(badge_data["name"]),
                    "description": badge_data["description"],
                    "category": badge_data["category"],
                    "icon": badge_data["icon"],
                    "points_reward": badge_data["points"],
                    "is_active": True,
                },
            )
            if created:
                created_count += 1
                self.stdout.write(
                    f"  ✓ {badge.name} ({badge.get_category_display()}) - {badge.points_reward} pts"
                )

        self.stdout.write(
            self.style.SUCCESS(f"\n✅ {created_count} nouveaux badges marocains créés!")
        )
        self.stdout.write(self.style.SUCCESS(f"Total badges: {Badge.objects.count()}"))
