# Generated by Django 5.2.8 on 2025-11-05 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("streak", "Streak"),
                            ("milestone", "Milestone"),
                            ("community", "Community"),
                            ("template", "Template"),
                            ("coaching", "Coaching"),
                            ("special", "Special"),
                        ],
                        default="special",
                        max_length=20,
                        verbose_name="badge type",
                    ),
                ),
                (
                    "icon",
                    models.CharField(default="🏆", max_length=50, verbose_name="icon"),
                ),
                (
                    "icon_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="badges/",
                        verbose_name="icon image",
                    ),
                ),
                (
                    "requirement_type",
                    models.CharField(max_length=50, verbose_name="requirement type"),
                ),
                (
                    "requirement_value",
                    models.PositiveIntegerField(
                        default=0, verbose_name="requirement value"
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        default="common", max_length=20, verbose_name="rarity"
                    ),
                ),
                (
                    "xp_reward",
                    models.PositiveIntegerField(default=0, verbose_name="XP reward"),
                ),
                (
                    "times_awarded",
                    models.PositiveIntegerField(
                        default=0, verbose_name="times awarded"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "badge",
                "verbose_name_plural": "badges",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "leaderboard_type",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("category", "Category"),
                            ("community", "Community"),
                        ],
                        default="global",
                        max_length=20,
                        verbose_name="leaderboard type",
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("all_time", "All Time"),
                        ],
                        default="all_time",
                        max_length=20,
                        verbose_name="timeframe",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="category"
                    ),
                ),
                (
                    "community_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="community ID"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "leaderboard",
                "verbose_name_plural": "leaderboards",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "quest_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("special", "Special"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="quest type",
                    ),
                ),
                (
                    "requirement_action",
                    models.CharField(max_length=100, verbose_name="requirement action"),
                ),
                (
                    "requirement_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="requirement count"
                    ),
                ),
                (
                    "xp_reward",
                    models.PositiveIntegerField(default=50, verbose_name="XP reward"),
                ),
                (
                    "credit_reward",
                    models.PositiveIntegerField(
                        default=0, verbose_name="credit reward"
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="start date")),
                ("end_date", models.DateTimeField(verbose_name="end date")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "quest",
                "verbose_name_plural": "quests",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="UserQuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "progress",
                    models.PositiveIntegerField(default=0, verbose_name="progress"),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="completed"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "user quest",
                "verbose_name_plural": "user quests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "awarded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="awarded at"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="is featured"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to="gamification.badge",
                    ),
                ),
            ],
            options={
                "verbose_name": "user badge",
                "verbose_name_plural": "user badges",
                "ordering": ["-awarded_at"],
            },
        ),
    ]
