# Generated by Django 5.2.8 on 2025-11-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_url",
                    models.CharField(max_length=500, verbose_name="URL de la page"),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("ARTWORK", "Œuvre"),
                            ("GALLERY", "Galerie"),
                            ("PROFILE", "Profil"),
                            ("HOMEPAGE", "Page d'accueil"),
                        ],
                        max_length=50,
                        verbose_name="type de page",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "referrer",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="référent"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
            ],
            options={
                "verbose_name": "vue de page",
                "verbose_name_plural": "vues de page",
                "ordering": ["-created_at"],
            },
        ),
    ]
